# Generated by Django 4.0.1 on 2022-01-11 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='creation',
        ),
    ]
