# Generated by Django 4.0.1 on 2022-01-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_remove_modulo_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='slug',
            field=models.SlugField(max_length=64, null=True),
        ),
    ]
