# Generated by Django 4.0.1 on 2022-01-21 02:05

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0008_alter_aula_vimeo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='teste',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=8),
        ),
    ]
